name: "Kubernetes Upgrade Issues"

on:
  workflow_dispatch:
    inputs:
      upgrade-version:
        description: 'The target EKS upgrade version (e.g., 1.32)'
        required: true

env:
  GHPKEY: ${{ secrets.GHAPKEY }}
  GHAID: ${{ secrets.GHAAID }}
  GHIID: ${{ secrets.GHAIID }}
jobs: 
  create-upgrade-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Set up Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version: '1.25'

      - name: Install Dependencies
        run: go mod tidy

      - name: Run Creation of Upgrade Issues
        run: go run cmd/create-upgrade-issues/main.go -upgrade-version ${{ github.event.inputs.upgrade-version }} -owner ${{ github.event.repository.owner }} -repo ${{ github.event.repository.name }}

      - name: Notify Slack channel of job status
        if: always()
        uses: slackapi/slack-github-action@91efab103c0de0a537f72a35f6b8cda0ee76bf0a # v2.1.1
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            text: "*Upgrade Issues Creation*: ${{ job.status }}"
            blocks:
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: "Upgrade Issues Creation: ${{ job.status }}"